### ISSUE TITLE
Why are DIDs produced by hashing the DID doc and not just public key

### ISSUE THREAD

**Issue by lovesh** [openssi/peer-did-method-spec#78]
It's a little odd that DIDs are derived from a DID doc which is supposed to contain the DID in the first place. What is wrong with hashing the public key?

**Comment by dhh1128** [comment]
There can be more than one public key in a DID doc. It's not obvious which one we would hash. If we don't allow multiple keys in the genesis version of the DID doc, then we are going to force everybody to update their DID docs immediately after creation, since most domains are going to contain multiple keys. Also, this would mean that genesis versions of DID docs couldn't contain M-of-N policies or highly privileged offline/recovery keys, which would be dangerous.

We could say, "just hash the *first* key in the DID doc, whatever it is." This would get us around the first difficulty. But we'd have a new problem, which is that the DID itself no longer gives MITM protection; there's no strong binding between the *full* content of the DID doc and the DID value itself. Mallory could intercept the DID doc and add a few extra keys, in addition to the one that provided the DID.

Of course we can get around this second problem by requiring the initial DID doc to be signed. But that leads us to the third problem, which is that a signature binds the DID doc to a specific crypto mechanism. If the first key in the DID doc is an Ed25519 key, then the signature that proves everything is peachy is going to be an Ed25519-based thing. If RSA, then RSA. If Secp256k1, then Secp256k1.

By making the DID derive from the initial delta, we can validate the DID doc and be tamper evident without any crypto suite. This turns out to be a nice property--especially considering that this DID method is supposed to work for all the different crypto communities, not just the Indy/Sovrin world where you and I have spent most of our time.

It is also the case that every delta we add to the doc needs to have a hash (a strong content-based, tamper-resistant identifier) anyway, to make the synchronization protocol work. And since the genesis DID doc is just deltas[0], using this hash as the DID makes the handling simpler and more consistent; making the DID come from an algorithm entirely different from the identifiers for each delta is just extra work.

**Comment by dhh1128** [comment]
Closing this after a personal conversation (I'm under the impression that the question was satisfactorily answered by the above txt). If that's not the case, please reopen, @lovesh .
